# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit', '0002_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='In miles', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(default=1, help_text='In minutes'),
        ),
    ]
