# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_auto_20160207_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetypes',
            name='singular',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
